backend:
  name: git-gateway
  branch: master
  accept_roles:
    - admin
    - editor

media_folder: "images/uploads"

collections:
  - name: "books" # Used in routes, e.g., /admin/collections/blog
    label: "Books" # Used in the UI
    folder: "_books" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "ISBN", name: "isbn", widget: "number"}
